name: EasysetskinAPI
version: 1.0.0
main: mahdikarami8484\EasysetskinAPI\main
api: 4.0.0
description: API for set skin player easy
author: mahdikarami8484

commands:
  easysetskin:
    description: for see about developer
    permission: easysetskinapi.command

permissions:
  easysetskinapi.command:
    description: Allow using easysetskinapi command
    default: op