name: easySetSkin
version: 1.0.0
main: easySetSkin\main
api: 4.0.0
description: for easy set skin
author: mahdikarami8484


commands:
  easysetskin:
    description: for see about developer
    permission: easysetskin.command

permissions:
  easysetskin.command:
    description: Allow using easysetskin command
    default: true
